services:
  app:
    container_name: habitgram_app
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV:-production}
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - PHP_IDE_CONFIG=serverName=Habitgram
    volumes:
      - .:/var/www/html
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
    networks:
      - habitgram_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:80/up" ]
      interval: 30s
      timeout: 10s
      retries: 6

  db:
    container_name: habitgram_db
    build: .docker/db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    shm_size: 1g
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - habitgram_network
    volumes:
      - .docker/db/data:/var/lib/postgresql/data
      - .docker/db/init/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "5"

  redis:
    container_name: habitgram_redis
    build: .docker/redis
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - "${REDIS_PORT:-6379}"
    networks:
      - habitgram_network
    volumes:
      - .docker/redis/data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  mailpit:
    container_name: habitgram_mailpit
    build: .docker/mailpit
    ports:
      - '${FORWARD_MAILPIT_PORT:-8025}:8025'
    user: root
    restart: unless-stopped
    environment:
      MP_WEBROOT: /mailpit/
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    volumes:
      - .docker/mailpit/data:/data
    networks:
      - habitgram_network
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--spider", "http://0.0.0.0:8025/mailpit/" ]
      retries: 3
      timeout: 5s

networks:
  habitgram_network:
    name: habitgram_network
    driver: bridge